version: "3.3"

services:
    socket.server:
      build: .
      entrypoint: ["socket-server", "0.0.0.0", "12345"]

    socket.client:
      build: .
      depends_on:
        - socket.server
      entrypoint: ["/bin/bash", "-c", "echo hello | socket-client socket.server 12345 -"]