version: "3.3"

services:
    socket.server:
      build: .
      entrypoint: ["socket-server"]
      ports:
        - '12345:12345'

    socket.client:
      build: .
      depends_on:
        - socket.server
      entrypoint: ["echo", "hello | socket-client -"]
      network_mode: "service:socket.server"